# Generated by Django 4.2.1 on 2023-05-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
    ]
