# Generated by Django 4.2.1 on 2023-05-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
