# Generated by Django 4.2.1 on 2023-05-27 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_delete_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_rating',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='article_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_rating',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='time_in',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_choice',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_title',
        ),
        migrations.AddField(
            model_name='post',
            name='head_name',
            field=models.CharField(default=datetime.datetime(2023, 5, 27, 7, 7, 55, 563300, tzinfo=datetime.timezone.utc), max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='news', max_length=2),
        ),
    ]
