# Generated by Django 4.2.1 on 2023-07-09 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_rate_author_author_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPortalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.postcategory')),
                ('news_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
    ]
